name: Deploy to EC2

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        run: ssh -o StrictHostKeyChecking=no ec2-user@18.203.81.35 'cd /home/ec2-user/em-be && git pull && sudo systemctl restart myapp'
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}
